language: c
sudo: required

compiler:
  - clang
  - gcc

before_install:
  - sudo service postgresql stop
  - sudo pg_ctlcluster $POSTGRESQL_VERSION main start
  - pg_lsclusters
  - sudo apt-get install postgresql-server-dev-$POSTGRESQL_VERSION
  - git clone https://github.com/google/brotli.git
  - pushd brotli
  - ./configure-cmake
  - make
  - popd

env:
  global:
    - PGDATABASE=postgres
    - PGUSER=postgres

  matrix:
    - POSTGRESQL_VERSION=9.6
    - POSTGRESQL_VERSION=10

script:
  - make
  - sudo make install
  - make installcheck || (cat regression.diffs && /bin/false)
