language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo service postgresql stop
  - sudo service postgresql start $POSTGRESQL_VERSION
  - sudo apt-get install postgresql-server-dev-$POSTGRESQL_VERSION
  - git clone https://github.com/google/brotli.git
  - pushd brotli
  - ./configure-cmake
  - make
  - popd

env:
  global:
    - PGDATABASE=postgres
    - PGUSER=postgres

  matrix:
    - POSTGRESQL_VERSION=12
    - POSTGRESQL_VERSION=11

script:
  - make
  - sudo make install
  - make installcheck || (cat regression.diffs && /bin/false)
